"""
Centralized mappings for the thesis project.

All hardcoded location lists, country name mappings, SDI quintile assignments,
SDI numeric values, and feature definitions used across notebooks are
consolidated here so that every notebook can simply:

    from mappings import <NAME>

instead of redefining the same constants.
"""

# ---------------------------------------------------------------------------
# 1. IRAN_PROVINCES  --  31 provinces of Iran
# Source: notebooks 2 & 3
# ---------------------------------------------------------------------------
IRAN_PROVINCES = [
    'Alborz',
    'Ardebil',
    'Bushehr',
    'Chahar Mahaal and Bakhtiari',
    'East Azarbayejan',
    'Fars',
    'Gilan',
    'Golestan',
    'Hamadan',
    'Hormozgan',
    'Ilam',
    'Isfahan',
    'Kerman',
    'Kermanshah',
    'Khorasan-e-Razavi',
    'Khuzestan',
    'Kohgiluyeh and Boyer-Ahmad',
    'Kurdistan',
    'Lorestan',
    'Markazi',
    'Mazandaran',
    'North Khorasan',
    'Qazvin',
    'Qom',
    'Semnan',
    'Sistan and Baluchistan',
    'South Khorasan',
    'Tehran',
    'West Azarbayejan',
    'Yazd',
    'Zanjan',
]

# ---------------------------------------------------------------------------
# 2. WB_REGIONS  --  7 World Bank regions used in the analysis
# Source: notebook 3 (variable `wb`)
# ---------------------------------------------------------------------------
WB_REGIONS = [
    'Europe & Central Asia - WB',
    'Middle East & North Africa - WB',
    'Sub-Saharan Africa - WB',
    'East Asia & Pacific - WB',
    'South Asia - WB',
    'Latin America & Caribbean - WB',
    'North America',
]

# ---------------------------------------------------------------------------
# 3. SDI_QUINTILES  --  5 Socio-Demographic Index groups
# Source: notebook 3 (variable `sdi`)
# ---------------------------------------------------------------------------
SDI_QUINTILES = [
    'High SDI',
    'High-middle SDI',
    'Middle SDI',
    'Low-middle SDI',
    'Low SDI',
]

# ---------------------------------------------------------------------------
# 4. COUNTRY_LIST  --  ~200 countries used in analysis
# Source: notebook 3 (variable `country`)
# Note: includes 'Global' as a pseudo-location for aggregate rows
# ---------------------------------------------------------------------------
COUNTRY_LIST = [
    'Zambia',
    'Uganda',
    'Lesotho',
    'Namibia',
    'Singapore',
    'Taiwan',
    'Poland',
    'Luxembourg',
    'Netherlands',
    'Suriname',
    'Belgium',
    'Norway',
    'Sweden',
    'Jamaica',
    'Costa Rica',
    'Guyana',
    'Peru',
    'Canada',
    'El Salvador',
    'Ecuador',
    'The Bahamas',
    'Colombia',
    'Guatemala',
    'Honduras',
    'Albania',
    'Trinidad and Tobago',
    'United Arab Emirates',
    'United States',
    'United Kingdom',
    'Bolivia',
    'Panama',
    'Cuba',
    'Argentina',
    'Nicaragua',
    'The Gambia',
    'Sierra Leone',
    'Senegal',
    'Mali',
    'Niger',
    'Nigeria',
    'Sao Tome and Principe',
    'Mauritania',
    'American Samoa',
    'Samoa',
    'Belarus',
    'Moldova',
    'Indonesia',
    'Lithuania',
    'Papua New Guinea',
    'Kiribati',
    'Turkmenistan',
    'South Korea',
    'North Korea',
    'Japan',
    'Iran',
    'Iraq',
    'Kuwait',
    'Algeria',
    'Turkey',
    'Armenia',
    'Guam',
    'Austria',
    'Italy',
    'Ireland',
    'Iceland',
    'Malta',
    'Spain',
    'Germany',
    'Israel',
    'Bhutan',
    'Angola',
    'Democratic Republic of the Congo',
    'Congo',
    'Ethiopia',
    'Kenya',
    'Madagascar',
    'Rwanda',
    'Mozambique',
    'Botswana',
    'Tanzania',
    'Seychelles',
    'Malawi',
    'Mauritius',
    'Eritrea',
    'Burundi',
    'Guinea-Bissau',
    'Liberia',
    'Ghana',
    'Afghanistan',
    'Nepal',
    'Pakistan',
    'Comoros',
    'India',
    'Equatorial Guinea',
    'Djibouti',
    'Jordan',
    'Benin',
    'Cape Verde',
    'Venezuela',
    "Cote d'Ivoire",
    'Cameroon',
    'Chad',
    'Vietnam',
    'Ukraine',
    'Russian Federation',
    'Romania',
    'Hungary',
    'Croatia',
    'Mongolia',
    'Sri Lanka',
    'Bulgaria',
    'Philippines',
    'Azerbaijan',
    'Brunei',
    'Serbia',
    'Australia',
    'China',
    'Fiji',
    'Virgin Islands, U.S.',
    'Bangladesh',
    'Yemen',
    'Somalia',
    'Zimbabwe',
    'Burkina Faso',
    'Andorra',
    'Brazil',
    'Saudi Arabia',
    'Egypt',
    'Syria',
    'Qatar',
    'Czech Republic',
    'Macedonia',
    'Kyrgyzstan',
    'Montenegro',
    'Libya',
    'Myanmar',
    'Cambodia',
    'Greenland',
    'Chile',
    'Federated States of Micronesia',
    'Marshall Islands',
    'Vanuatu',
    'Dominican Republic',
    'Portugal',
    'Timor-Leste',
    'Thailand',
    'Denmark',
    'Grenada',
    'Solomon Islands',
    'Paraguay',
    'France',
    'Estonia',
    'Belize',
    'Maldives',
    'Gabon',
    'South Africa',
    'Saint Lucia',
    'Antigua and Barbuda',
    'New Zealand',
    'Malaysia',
    'Latvia',
    'Kazakhstan',
    'Togo',
    'Bermuda',
    'Laos',
    'Tonga',
    'Bahrain',
    'Morocco',
    'Bosnia and Herzegovina',
    'Cyprus',
    'Haiti',
    'Switzerland',
    'Northern Mariana Islands',
    'Finland',
    'Lebanon',
    'Palestine',
    'Barbados',
    'Oman',
    'Tunisia',
    'Central African Republic',
    'Guinea',
    'Dominica',
    'Uzbekistan',
    'Slovenia',
    'Slovakia',
    'Saint Vincent and the Grenadines',
    'Tajikistan',
    'South Sudan',
    'Sudan',
    'Puerto Rico',
    'Georgia',
    'Mexico',
    'Uruguay',
    'Eswatini',
    'Greece',
    'Global',
]

# ---------------------------------------------------------------------------
# 5. SDI_COUNTRY_MAPPING  --  country -> SDI quintile (Low / Low-middle /
#    Middle / High-middle / High)
# Source: notebook 5 (variable `sdi_mapping`)
# ---------------------------------------------------------------------------
SDI_COUNTRY_MAPPING = {
    'Zambia': 'Low',
    'Uganda': 'Low',
    'Lesotho': 'Low',
    'Namibia': 'Low-middle',
    'Singapore': 'High',
    'Taiwan': 'High',
    'Poland': 'High-middle',
    'Luxembourg': 'High',
    'Netherlands': 'High',
    'Suriname': 'Middle',
    'Belgium': 'High',
    'Norway': 'High',
    'Sweden': 'High',
    'Jamaica': 'Middle',
    'Costa Rica': 'Middle',
    'Guyana': 'Low-middle',
    'Peru': 'Middle',
    'Canada': 'High',
    'El Salvador': 'Middle',
    'Ecuador': 'Middle',
    'The Bahamas': 'High-middle',
    'Colombia': 'Middle',
    'Guatemala': 'Low-middle',
    'Honduras': 'Low-middle',
    'Albania': 'Middle',
    'Trinidad and Tobago': 'High-middle',
    'United Arab Emirates': 'High',
    'United States': 'High',
    'United Kingdom': 'High',
    'Bolivia': 'Low-middle',
    'Panama': 'High-middle',
    'Cuba': 'High-middle',
    'Argentina': 'High-middle',
    'Nicaragua': 'Low-middle',
    'The Gambia': 'Low',
    'Sierra Leone': 'Low',
    'Senegal': 'Low-middle',
    'Mali': 'Low',
    'Niger': 'Low',
    'Nigeria': 'Low',
    'Sao Tome and Principe': 'Low',
    'Mauritania': 'Low-middle',
    'American Samoa': 'Middle',
    'Samoa': 'Middle',
    'Belarus': 'High-middle',
    'Moldova': 'Middle',
    'Indonesia': 'Middle',
    'Lithuania': 'High-middle',
    'Papua New Guinea': 'Low',
    'Kiribati': 'Low',
    'Turkmenistan': 'Middle',
    'South Korea': 'High',
    'North Korea': 'Middle',
    'Japan': 'High',
    'Iran': 'High-middle',
    'Iraq': 'Low-middle',
    'Kuwait': 'High-middle',
    'Algeria': 'High-middle',
    'Turkey': 'High-middle',
    'Armenia': 'Middle',
    'Guam': 'High-middle',
    'Austria': 'High',
    'Italy': 'High',
    'Ireland': 'High',
    'Iceland': 'High',
    'Malta': 'High',
    'Spain': 'High',
    'Germany': 'High',
    'Israel': 'High',
    'Bhutan': 'Low-middle',
    'Angola': 'Low',
    'Democratic Republic of the Congo': 'Low',
    'Congo': 'Low',
    'Ethiopia': 'Low',
    'Kenya': 'Low-middle',
    'Madagascar': 'Low',
    'Rwanda': 'Low',
    'Mozambique': 'Low',
    'Botswana': 'Middle',
    'Tanzania': 'Low-middle',
    'Seychelles': 'High-middle',
    'Malawi': 'Low',
    'Mauritius': 'High-middle',
    'Eritrea': 'Low',
    'Burundi': 'Low',
    'Guinea-Bissau': 'Low',
    'Liberia': 'Low',
    'Ghana': 'Low-middle',
    'Afghanistan': 'Low',
    'Nepal': 'Low-middle',
    'Pakistan': 'Low-middle',
    'Comoros': 'Low-middle',
    'India': 'Low-middle',
    'Equatorial Guinea': 'Low-middle',
    'Djibouti': 'Low',
    'Jordan': 'Middle',
    'Benin': 'Low',
    'Cape Verde': 'Middle',
    'Venezuela': 'Middle',
    "Cote d'Ivoire": 'Low-middle',
    'Cameroon': 'Low-middle',
    'Chad': 'Low',
    'Vietnam': 'Middle',
    'Ukraine': 'Middle',
    'Russian Federation': 'High-middle',
    'Romania': 'Middle',
    'Hungary': 'High-middle',
    'Croatia': 'High-middle',
    'Mongolia': 'Middle',
    'Sri Lanka': 'High-middle',
    'Bulgaria': 'Middle',
    'Philippines': 'Middle',
    'Azerbaijan': 'Middle',
    'Brunei': 'High-middle',
    'Serbia': 'Middle',
    'Australia': 'High',
    'China': 'High-middle',
    'Fiji': 'Middle',
    'Virgin Islands, U.S.': 'High',
    'Bangladesh': 'Low-middle',
    'Yemen': 'Low',
    'Somalia': 'Low',
    'Zimbabwe': 'Low',
    'Burkina Faso': 'Low',
    'Andorra': 'High',
    'Brazil': 'High-middle',
    'Saudi Arabia': 'High-middle',
    'Egypt': 'Middle',
    'Syria': 'Low-middle',
    'Qatar': 'High',
    'Czech Republic': 'High',
    'Macedonia': 'Middle',
    'Kyrgyzstan': 'Low-middle',
    'Montenegro': 'Middle',
    'Libya': 'Middle',
    'Myanmar': 'Low-middle',
    'Cambodia': 'Low-middle',
    'Greenland': 'High',
    'Chile': 'High',
    'Federated States of Micronesia': 'Low-middle',
    'Marshall Islands': 'Low-middle',
    'Vanuatu': 'Low',
    'Dominican Republic': 'Middle',
    'Portugal': 'High',
    'Timor-Leste': 'Low',
    'Thailand': 'Middle',
    'Denmark': 'High',
    'Grenada': 'Middle',
    'Solomon Islands': 'Low',
    'Paraguay': 'Middle',
    'France': 'High',
    'Estonia': 'High',
    'Belize': 'Middle',
    'Maldives': 'High-middle',
    'Gabon': 'Middle',
    'South Africa': 'High-middle',
    'Saint Lucia': 'Middle',
    'Antigua and Barbuda': 'High-middle',
    'New Zealand': 'High',
    'Malaysia': 'High-middle',
    'Latvia': 'High-middle',
    'Kazakhstan': 'Middle',
    'Togo': 'Low',
    'Bermuda': 'High',
    'Laos': 'Low-middle',
    'Tonga': 'Middle',
    'Bahrain': 'High',
    'Morocco': 'Middle',
    'Bosnia and Herzegovina': 'Middle',
    'Cyprus': 'High',
    'Haiti': 'Low',
    'Switzerland': 'High',
    'Northern Mariana Islands': 'High',
    'Finland': 'High',
    'Lebanon': 'Middle',
    'Palestine': 'Low-middle',
    'Barbados': 'High',
    'Oman': 'High-middle',
    'Tunisia': 'Middle',
    'Central African Republic': 'Low',
    'Guinea': 'Low',
    'Dominica': 'Middle',
    'Uzbekistan': 'Middle',
    'Slovenia': 'High',
    'Slovakia': 'High',
    'Saint Vincent and the Grenadines': 'Middle',
    'Tajikistan': 'Low-middle',
    'South Sudan': 'Low',
    'Sudan': 'Low',
    'Puerto Rico': 'High',
    'Georgia': 'Middle',
    'Mexico': 'High-middle',
    'Uruguay': 'High',
    'Eswatini': 'Middle',
    'Greece': 'High',
}

# ---------------------------------------------------------------------------
# 6. FEATURES_3 / FEATURES_4  --  PCA feature sets
# Source: notebook 3
# ---------------------------------------------------------------------------
FEATURES_3 = ['MIR', 'YLLtoYLD', 'DALtoPER']
FEATURES_4 = ['MIR', 'YLLtoYLD', 'DALtoPER', 'PERtoINC']

# ---------------------------------------------------------------------------
# 7. GBD_REGIONS  --  21 GBD regions
# Source: notebook 2 (IHME location hierarchy, type "21 GBD Regions")
# ---------------------------------------------------------------------------
GBD_REGIONS = [
    'South Asia',
    'Central Sub-Saharan Africa',
    'High-income Asia Pacific',
    'Central Latin America',
    'Oceania',
    'Central Europe',
    'Southern Latin America',
    'High-income North America',
    'Eastern Sub-Saharan Africa',
    'Eastern Europe',
    'Southeast Asia',
    'East Asia',
    'Andean Latin America',
    'Central Asia',
    'Tropical Latin America',
    'Western Sub-Saharan Africa',
    'North Africa and Middle East',
    'Australasia',
    'Caribbean',
    'Southern Sub-Saharan Africa',
    'Western Europe',
]

# ---------------------------------------------------------------------------
# 8. WHO_REGIONS  --  6 WHO regions
# Source: notebook 2 (IHME location hierarchy, type "WHO Regions")
# ---------------------------------------------------------------------------
WHO_REGIONS = [
    'African Region',
    'South-East Asia Region',
    'Western Pacific Region',
    'European Region',
    'Eastern Mediterranean Region',
    'Region of the Americas',
]

# ---------------------------------------------------------------------------
# 9. WORLD_BANK_INCOME_LEVELS  --  4 World Bank income groups
# Source: notebook 2 (IHME location hierarchy)
# ---------------------------------------------------------------------------
WORLD_BANK_INCOME_LEVELS = [
    'World Bank High Income',
    'World Bank Low Income',
    'World Bank Upper Middle Income',
    'World Bank Lower Middle Income',
]

# ---------------------------------------------------------------------------
# 10. WORLD_REGIONS_4  --  4 broad world regions
# Source: notebook 2
# ---------------------------------------------------------------------------
WORLD_REGIONS_4 = [
    'Africa',
    'America',
    'Asia',
    'Europe',
]

# ---------------------------------------------------------------------------
# 11. SDI_VALUE_MAP_2021  --  country -> numeric SDI value for 2021
# Source: notebook 5 (variable `sdi_value_map_2021`)
# ---------------------------------------------------------------------------
SDI_VALUE_MAP_2021 = {
    'Zambia': 0.45,
    'Uganda': 0.46,
    'Lesotho': 0.47,
    'Namibia': 0.55,
    'Singapore': 0.89,
    'Taiwan': 0.86,
    'Poland': 0.79,
    'Luxembourg': 0.91,
    'Netherlands': 0.89,
    'Suriname': 0.64,
    'Belgium': 0.88,
    'Norway': 0.90,
    'Sweden': 0.89,
    'Jamaica': 0.67,
    'Costa Rica': 0.70,
    'Guyana': 0.58,
    'Peru': 0.70,
    'Canada': 0.90,
    'El Salvador': 0.66,
    'Ecuador': 0.68,
    'The Bahamas': 0.78,
    'Colombia': 0.70,
    'Guatemala': 0.58,
    'Honduras': 0.57,
    'Albania': 0.68,
    'Trinidad and Tobago': 0.78,
    'United Arab Emirates': 0.85,
    'United States': 0.89,
    'United Kingdom': 0.88,
    'Bolivia': 0.56,
    'Panama': 0.77,
    'Cuba': 0.80,
    'Argentina': 0.78,
    'Nicaragua': 0.56,
    'The Gambia': 0.44,
    'Sierra Leone': 0.41,
    'Senegal': 0.48,
    'Mali': 0.43,
    'Niger': 0.40,
    'Nigeria': 0.45,
    'Sao Tome and Principe': 0.46,
    'Mauritania': 0.49,
    'American Samoa': 0.66,
    'Samoa': 0.65,
    'Belarus': 0.76,
    'Moldova': 0.69,
    'Indonesia': 0.68,
    'Lithuania': 0.80,
    'Papua New Guinea': 0.46,
    'Kiribati': 0.45,
    'Turkmenistan': 0.69,
    'South Korea': 0.85,
    'North Korea': 0.65,
    'Japan': 0.89,
    'Iran': 0.76,
    'Iraq': 0.58,
    'Kuwait': 0.83,
    'Algeria': 0.77,
    'Turkey': 0.78,
    'Armenia': 0.70,
    'Guam': 0.79,
    'Austria': 0.88,
    'Italy': 0.87,
    'Ireland': 0.88,
    'Iceland': 0.89,
    'Malta': 0.88,
    'Spain': 0.87,
    'Germany': 0.88,
    'Israel': 0.87,
    'Bhutan': 0.55,
    'Angola': 0.46,
    'Democratic Republic of the Congo': 0.43,
    'Congo': 0.45,
    'Ethiopia': 0.46,
    'Kenya': 0.49,
    'Madagascar': 0.45,
    'Rwanda': 0.46,
    'Mozambique': 0.44,
    'Botswana': 0.62,
    'Tanzania': 0.49,
    'Seychelles': 0.77,
    'Malawi': 0.46,
    'Mauritius': 0.78,
    'Eritrea': 0.43,
    'Burundi': 0.42,
    'Guinea-Bissau': 0.43,
    'Liberia': 0.44,
    'Ghana': 0.49,
    'Afghanistan': 0.43,
    'Nepal': 0.51,
    'Pakistan': 0.53,
    'Comoros': 0.52,
    'India': 0.57,
    'Equatorial Guinea': 0.54,
    'Djibouti': 0.47,
    'Jordan': 0.69,
    'Benin': 0.46,
    'Cape Verde': 0.68,
    'Venezuela': 0.68,
    "Cote d'Ivoire": 0.50,
    'Cameroon': 0.52,
    'Chad': 0.43,
    'Vietnam': 0.68,
    'Ukraine': 0.71,
    'Russian Federation': 0.78,
    'Romania': 0.72,
    'Hungary': 0.79,
    'Croatia': 0.80,
    'Mongolia': 0.68,
    'Sri Lanka': 0.74,
    'Bulgaria': 0.72,
    'Philippines': 0.68,
    'Azerbaijan': 0.70,
    'Brunei': 0.80,
    'Serbia': 0.72,
    'Australia': 0.89,
    'China': 0.78,
    'Fiji': 0.67,
    'Virgin Islands, U.S.': 0.86,
    'Bangladesh': 0.55,
    'Yemen': 0.46,
    'Somalia': 0.41,
    'Zimbabwe': 0.48,
    'Burkina Faso': 0.44,
    'Andorra': 0.89,
    'Brazil': 0.78,
    'Saudi Arabia': 0.80,
    'Egypt': 0.69,
    'Syria': 0.54,
    'Qatar': 0.86,
    'Czech Republic': 0.83,
    'Macedonia': 0.70,
    'Kyrgyzstan': 0.55,
    'Montenegro': 0.70,
    'Libya': 0.69,
    'Myanmar': 0.56,
    'Cambodia': 0.54,
    'Greenland': 0.85,
    'Chile': 0.81,
    'Federated States of Micronesia': 0.55,
    'Marshall Islands': 0.55,
    'Vanuatu': 0.44,
    'Dominican Republic': 0.67,
    'Portugal': 0.87,
    'Timor-Leste': 0.40,
    'Thailand': 0.68,
    'Denmark': 0.90,
    'Grenada': 0.67,
    'Solomon Islands': 0.42,
    'Paraguay': 0.67,
    'France': 0.90,
    'Estonia': 0.87,
    'Belize': 0.67,
    'Maldives': 0.77,
    'Gabon': 0.67,
    'South Africa': 0.78,
    'Saint Lucia': 0.67,
    'Antigua and Barbuda': 0.78,
    'New Zealand': 0.90,
    'Malaysia': 0.79,
    'Latvia': 0.79,
    'Kazakhstan': 0.67,
    'Togo': 0.40,
    'Bermuda': 0.90,
    'Laos': 0.54,
    'Tonga': 0.67,
    'Bahrain': 0.85,
    'Morocco': 0.67,
    'Bosnia and Herzegovina': 0.67,
    'Cyprus': 0.87,
    'Haiti': 0.42,
    'Switzerland': 0.90,
    'Northern Mariana Islands': 0.90,
    'Finland': 0.90,
    'Lebanon': 0.67,
    'Palestine': 0.54,
    'Barbados': 0.90,
    'Oman': 0.79,
    'Tunisia': 0.67,
    'Central African Republic': 0.40,
    'Guinea': 0.42,
    'Dominica': 0.67,
    'Uzbekistan': 0.67,
    'Slovenia': 0.90,
    'Slovakia': 0.90,
    'Saint Vincent and the Grenadines': 0.67,
    'Tajikistan': 0.55,
    'South Sudan': 0.40,
    'Sudan': 0.40,
    'Puerto Rico': 0.90,
    'Georgia': 0.67,
    'Mexico': 0.79,
    'Uruguay': 0.90,
    'Eswatini': 0.67,
    'Greece': 0.90,
}

# ---------------------------------------------------------------------------
# 12. COUNTRY_NAME_MAPPING  --  GBD formal names -> standardised ISO short
#     names used throughout the project
# Source: notebook 2 (original_names -> standardized_names)
# ---------------------------------------------------------------------------
COUNTRY_NAME_MAPPING = {
    'Southern Sub-Saharan Africa': 'Southern Sub-Saharan Africa',
    'Western Sub-Saharan Africa': 'Western Sub-Saharan Africa',
    'Republic of Zambia': 'Zambia',
    'Republic of Uganda': 'Uganda',
    'Kingdom of Lesotho': 'Lesotho',
    'Republic of Namibia': 'Namibia',
    'Republic of Singapore': 'Singapore',
    'Taiwan (Province of China)': 'Taiwan',
    'Republic of Poland': 'Poland',
    'Grand Duchy of Luxembourg': 'Luxembourg',
    'Kingdom of the Netherlands': 'Netherlands',
    'Republic of Suriname': 'Suriname',
    'Kingdom of Belgium': 'Belgium',
    'Kingdom of Norway': 'Norway',
    'Kingdom of Sweden': 'Sweden',
    'Jamaica': 'Jamaica',
    'Republic of Costa Rica': 'Costa Rica',
    'Republic of Guyana': 'Guyana',
    'Republic of Peru': 'Peru',
    'Canada': 'Canada',
    'Republic of El Salvador': 'El Salvador',
    'Republic of Ecuador': 'Ecuador',
    'Commonwealth of the Bahamas': 'The Bahamas',
    'Republic of Colombia': 'Colombia',
    'Republic of Guatemala': 'Guatemala',
    'Republic of Honduras': 'Honduras',
    'Republic of Albania': 'Albania',
    'Republic of Trinidad and Tobago': 'Trinidad and Tobago',
    'United Arab Emirates': 'United Arab Emirates',
    'United States of America': 'United States',
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'Plurinational State of Bolivia': 'Bolivia',
    'Republic of Panama': 'Panama',
    'Republic of Cuba': 'Cuba',
    'Argentine Republic': 'Argentina',
    'Republic of Nicaragua': 'Nicaragua',
    'Republic of the Gambia': 'The Gambia',
    'Republic of Sierra Leone': 'Sierra Leone',
    'Republic of Senegal': 'Senegal',
    'Republic of Mali': 'Mali',
    'Republic of the Niger': 'Niger',
    'Federal Republic of Nigeria': 'Nigeria',
    'Democratic Republic of Sao Tome and Principe': 'Sao Tome and Principe',
    'Islamic Republic of Mauritania': 'Mauritania',
    'American Samoa': 'American Samoa',
    'Independent State of Samoa': 'Samoa',
    'Republic of Belarus': 'Belarus',
    'Republic of Moldova': 'Moldova',
    'Republic of Indonesia': 'Indonesia',
    'Republic of Lithuania': 'Lithuania',
    'Independent State of Papua New Guinea': 'Papua New Guinea',
    'Republic of Kiribati': 'Kiribati',
    'Turkmenistan': 'Turkmenistan',
    'Republic of Korea': 'South Korea',
    "Democratic People's Republic of Korea": 'North Korea',
    'Japan': 'Japan',
    'Islamic Republic of Iran': 'Iran',
    'Republic of Iraq': 'Iraq',
    'State of Kuwait': 'Kuwait',
    "People's Democratic Republic of Algeria": 'Algeria',
    'Republic of Turkey': 'Turkey',
    'Republic of Armenia': 'Armenia',
    'Global': 'Global',
    'Guam': 'Guam',
    'Republic of Austria': 'Austria',
    'Republic of Italy': 'Italy',
    'Ireland': 'Ireland',
    'Republic of Iceland': 'Iceland',
    'Republic of Malta': 'Malta',
    'Kingdom of Spain': 'Spain',
    'Federal Republic of Germany': 'Germany',
    'State of Israel': 'Israel',
    'Kingdom of Bhutan': 'Bhutan',
    'Republic of Angola': 'Angola',
    'Democratic Republic of the Congo': 'Democratic Republic of the Congo',
    'Republic of the Congo': 'Congo',
    'Federal Democratic Republic of Ethiopia': 'Ethiopia',
    'Republic of Kenya': 'Kenya',
    'Republic of Madagascar': 'Madagascar',
    'Republic of Rwanda': 'Rwanda',
    'Republic of Mozambique': 'Mozambique',
    'Republic of Botswana': 'Botswana',
    'United Republic of Tanzania': 'Tanzania',
    'Republic of Seychelles': 'Seychelles',
    'Republic of Malawi': 'Malawi',
    'Republic of Mauritius': 'Mauritius',
    'State of Eritrea': 'Eritrea',
    'Republic of Burundi': 'Burundi',
    'Republic of Guinea-Bissau': 'Guinea-Bissau',
    'Republic of Liberia': 'Liberia',
    'Republic of Ghana': 'Ghana',
    'Islamic Republic of Afghanistan': 'Afghanistan',
    'Federal Democratic Republic of Nepal': 'Nepal',
    'Islamic Republic of Pakistan': 'Pakistan',
    'Union of the Comoros': 'Comoros',
    'Republic of India': 'India',
    'Republic of Equatorial Guinea': 'Equatorial Guinea',
    'Republic of Djibouti': 'Djibouti',
    'Hashemite Kingdom of Jordan': 'Jordan',
    'Republic of Benin': 'Benin',
    'Republic of Cabo Verde': 'Cape Verde',
    'Bolivarian Republic of Venezuela': 'Venezuela',
    'Latin America & Caribbean - WB': 'Latin America & Caribbean - WB',
    "Republic of Cote d'Ivoire": "Cote d'Ivoire",
    'Republic of Cameroon': 'Cameroon',
    'Republic of Chad': 'Chad',
    'Socialist Republic of Viet Nam': 'Vietnam',
    'Ukraine': 'Ukraine',
    'Russian Federation': 'Russian Federation',
    'Romania': 'Romania',
    'Hungary': 'Hungary',
    'Republic of Croatia': 'Croatia',
    'Mongolia': 'Mongolia',
    'Democratic Socialist Republic of Sri Lanka': 'Sri Lanka',
    'Republic of Bulgaria': 'Bulgaria',
    'Republic of the Philippines': 'Philippines',
    'Republic of Azerbaijan': 'Azerbaijan',
    'Brunei Darussalam': 'Brunei',
    'Republic of Serbia': 'Serbia',
    'Australia': 'Australia',
    "People's Republic of China": 'China',
    'Republic of Fiji': 'Fiji',
    'United States Virgin Islands': 'Virgin Islands, U.S.',
    "People's Republic of Bangladesh": 'Bangladesh',
    'Republic of Yemen': 'Yemen',
    'Federal Republic of Somalia': 'Somalia',
    'Republic of Zimbabwe': 'Zimbabwe',
    'Burkina Faso': 'Burkina Faso',
    'Principality of Andorra': 'Andorra',
    'Federative Republic of Brazil': 'Brazil',
    'Kingdom of Saudi Arabia': 'Saudi Arabia',
    'Arab Republic of Egypt': 'Egypt',
    'Syrian Arab Republic': 'Syria',
    'State of Qatar': 'Qatar',
    'Czech Republic': 'Czech Republic',
    'North Macedonia': 'Macedonia',
    'Oceania': 'Oceania',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Montenegro': 'Montenegro',
    'State of Libya': 'Libya',
    'Republic of the Union of Myanmar': 'Myanmar',
    'Kingdom of Cambodia': 'Cambodia',
    'Greenland': 'Greenland',
    'Republic of Chile': 'Chile',
    'Federated States of Micronesia': 'Federated States of Micronesia',
    'Republic of the Marshall Islands': 'Marshall Islands',
    'Republic of Vanuatu': 'Vanuatu',
    'Dominican Republic': 'Dominican Republic',
    'Portuguese Republic': 'Portugal',
    'Democratic Republic of Timor-Leste': 'Timor-Leste',
    'Kingdom of Thailand': 'Thailand',
    'Kingdom of Denmark': 'Denmark',
    'Grenada': 'Grenada',
    'Solomon Islands': 'Solomon Islands',
    'Republic of Paraguay': 'Paraguay',
    'French Republic': 'France',
    'Republic of Estonia': 'Estonia',
    'Belize': 'Belize',
    'Republic of Maldives': 'Maldives',
    'Gabonese Republic': 'Gabon',
    'Republic of South Africa': 'South Africa',
    'Saint Lucia': 'Saint Lucia',
    'Antigua and Barbuda': 'Antigua and Barbuda',
    'New Zealand': 'New Zealand',
    'Malaysia': 'Malaysia',
    'Republic of Latvia': 'Latvia',
    'Republic of Kazakhstan': 'Kazakhstan',
    'High SDI': 'High SDI',
    'High-middle SDI': 'High-middle SDI',
    'Low-middle SDI': 'Low-middle SDI',
    'Low SDI': 'Low SDI',
    'Middle SDI': 'Middle SDI',
    'African Region': 'African Region',
    'South-East Asia Region': 'South-East Asia Region',
    'Western Pacific Region': 'Western Pacific Region',
    'European Region': 'European Region',
    'Eastern Mediterranean Region': 'Eastern Mediterranean Region',
    'Region of the Americas': 'Region of the Americas',
    'Europe & Central Asia - WB': 'Europe & Central Asia - WB',
    'Middle East & North Africa - WB': 'Middle East & North Africa - WB',
    'Sub-Saharan Africa - WB': 'Sub-Saharan Africa - WB',
    'East Asia & Pacific - WB': 'East Asia & Pacific - WB',
    'South Asia - WB': 'South Asia - WB',
    'Togolese Republic': 'Togo',
    'Central Asia': 'Central Asia',
    'Asia': 'Asia',
    'South Asia': 'South Asia',
    'Southeast Asia': 'Southeast Asia',
    'East Asia': 'East Asia',
    'Europe': 'Europe',
    'Eastern Europe': 'Eastern Europe',
    'Western Europe': 'Western Europe',
    'Central Europe': 'Central Europe',
    'Eastern Sub-Saharan Africa': 'Eastern Sub-Saharan Africa',
    'Central Sub-Saharan Africa': 'Central Sub-Saharan Africa',
    'High-income Asia Pacific': 'High-income Asia Pacific',
    'Andean Latin America': 'Andean Latin America',
    'Southern Latin America': 'Southern Latin America',
    'Central Latin America': 'Central Latin America',
    'Tropical Latin America': 'Tropical Latin America',
    'Africa': 'Africa',
    'World Bank High Income': 'World Bank High Income',
    'World Bank Low Income': 'World Bank Low Income',
    'World Bank Upper Middle Income': 'World Bank Upper Middle Income',
    'World Bank Lower Middle Income': 'World Bank Lower Middle Income',
    'High-income North America': 'High-income North America',
    'Bermuda': 'Bermuda',
    "Lao People's Democratic Republic": 'Laos',
    'Kingdom of Tonga': 'Tonga',
    'Kingdom of Bahrain': 'Bahrain',
    'Kingdom of Morocco': 'Morocco',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Republic of Cyprus': 'Cyprus',
    'Republic of Haiti': 'Haiti',
    'Swiss Confederation': 'Switzerland',
    'Northern Mariana Islands': 'Northern Mariana Islands',
    'Republic of Finland': 'Finland',
    'Lebanese Republic': 'Lebanon',
    'Palestine': 'Palestine',
    'Barbados': 'Barbados',
    'Sultanate of Oman': 'Oman',
    'Republic of Tunisia': 'Tunisia',
    'Central African Republic': 'Central African Republic',
    'Republic of Guinea': 'Guinea',
    'Commonwealth of Dominica': 'Dominica',
    'Republic of Uzbekistan': 'Uzbekistan',
    'Republic of Slovenia': 'Slovenia',
    'Slovak Republic': 'Slovakia',
    'Caribbean': 'Caribbean',
    'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'America': 'America',
    'North Africa and Middle East': 'North Africa and Middle East',
    'Australasia': 'Australasia',
    'Republic of Tajikistan': 'Tajikistan',
    'Republic of South Sudan': 'South Sudan',
    'Republic of Sudan': 'Sudan',
    'Puerto Rico': 'Puerto Rico',
    'Georgia': 'Georgia',
    'United Mexican States': 'Mexico',
    'Eastern Republic of Uruguay': 'Uruguay',
    'Kingdom of Eswatini': 'Eswatini',
    'Hellenic Republic': 'Greece',
    'North America': 'North America',
    # Iran provinces (pass-through -- same name in both systems)
    'Alborz': 'Alborz',
    'Ardebil': 'Ardebil',
    'Bushehr': 'Bushehr',
    'Chahar Mahaal and Bakhtiari': 'Chahar Mahaal and Bakhtiari',
    'East Azarbayejan': 'East Azarbayejan',
    'Fars': 'Fars',
    'Gilan': 'Gilan',
    'Golestan': 'Golestan',
    'Hamadan': 'Hamadan',
    'Hormozgan': 'Hormozgan',
    'Ilam': 'Ilam',
    'Isfahan': 'Isfahan',
    'Kerman': 'Kerman',
    'Kermanshah': 'Kermanshah',
    'Khorasan-e-Razavi': 'Khorasan-e-Razavi',
    'Khuzestan': 'Khuzestan',
    'Kohgiluyeh and Boyer-Ahmad': 'Kohgiluyeh and Boyer-Ahmad',
    'Kurdistan': 'Kurdistan',
    'Lorestan': 'Lorestan',
    'Markazi': 'Markazi',
    'Mazandaran': 'Mazandaran',
    'North Khorasan': 'North Khorasan',
    'Qazvin': 'Qazvin',
    'Qom': 'Qom',
    'Semnan': 'Semnan',
    'Sistan and Baluchistan': 'Sistan and Baluchistan',
    'South Khorasan': 'South Khorasan',
    'Tehran': 'Tehran',
    'West Azarbayejan': 'West Azarbayejan',
    'Yazd': 'Yazd',
    'Zanjan': 'Zanjan',
    # Territories that exist in the raw data
    'Hong Kong': 'Hong Kong',
    'Macao': 'Macao',
    'Channel Islands': 'Channel Islands',
}

# ---------------------------------------------------------------------------
# 13. HAQ_LOCATION_MAPPING  --  IHME iso_location_name -> HAQ location_name
# Source: notebook 2 (ihme_loc -> haq_locations, used for merging HAQ data)
# Only entries that differ between the two naming systems are shown; all
# identical pairs are omitted for brevity.
# ---------------------------------------------------------------------------
HAQ_LOCATION_MAPPING = {
    'The Bahamas': 'Bahamas',
    'Bolivia': 'Bolivia (Plurinational State of)',
    'Brunei': 'Brunei Darussalam',
    'Cape Verde': 'Cabo Verde',
    "Cote d'Ivoire": "Cote d'Ivoire",
    'Czech Republic': 'Czechia',
    'Federated States of Micronesia': 'Micronesia (Federated States of)',
    'Iran': 'Iran (Islamic Republic of)',
    'Laos': "Lao People's Democratic Republic",
    'South Korea': 'Republic of Korea',
    'Moldova': 'Republic of Moldova',
    'Syria': 'Syrian Arab Republic',
    'Taiwan': 'Taiwan (Province of China)',
    'The Gambia': 'Gambia',
    'Tanzania': 'United Republic of Tanzania',
    'United States': 'United States of America',
    'Venezuela': 'Venezuela (Bolivarian Republic of)',
    'Vietnam': 'Viet Nam',
    'Virgin Islands, U.S.': 'United States Virgin Islands',
    'North Korea': "Democratic People's Republic of Korea",
    'Macedonia': 'North Macedonia',
    'Turkey': 'Turkiye',
}

# ---------------------------------------------------------------------------
# 14. AGE_GROUPS  --  age groups used in the analysis
# Source: notebook 3 output
# ---------------------------------------------------------------------------
AGE_GROUPS = [
    '<5 years',
    '5-14 years',
    '15-49 years',
    '50-69 years',
    '70+ years',
    'Age-standardized',
    'All ages',
]

# ---------------------------------------------------------------------------
# 15. SEX_NAMES  --  sex categories in the data
# Source: notebook 3 output
# ---------------------------------------------------------------------------
SEX_NAMES = [
    'Both',
    'Female',
    'Male',
]

# ---------------------------------------------------------------------------
# 16. NON_COUNTRY_LOCATIONS  --  every location name in the IHME data that is
# NOT a sovereign country (regions, aggregates, subnational units). Used to
# filter the data down to a country-level analytic sample.
# ---------------------------------------------------------------------------
NON_COUNTRY_LOCATIONS = set(WB_REGIONS + SDI_QUINTILES + IRAN_PROVINCES + [
    'Global', 'Africa', 'America', 'Asia', 'Europe', 'Oceania',
    'South Asia', 'Central Asia', 'Southeast Asia', 'East Asia',
    'Eastern Europe', 'Western Europe', 'Central Europe',
    'Eastern Sub-Saharan Africa', 'Central Sub-Saharan Africa',
    'Southern Sub-Saharan Africa', 'Western Sub-Saharan Africa',
    'High-income Asia Pacific', 'High-income North America',
    'Andean Latin America', 'Central Latin America',
    'Southern Latin America', 'Tropical Latin America',
    'Caribbean', 'North Africa and Middle East', 'Australasia',
    'North America',
    'World Bank High Income', 'World Bank Low Income',
    'World Bank Upper Middle Income', 'World Bank Lower Middle Income',
    'African Region', 'South-East Asia Region', 'Western Pacific Region',
    'European Region', 'Eastern Mediterranean Region', 'Region of the Americas',
])
