#!/usr/bin/env python3
"""
Paper 1 Figure Generation Script
=================================
DS-TB Quality of Care Index (QCI) - Publication-quality figures
for a Lancet Global Health-style epidemiology paper.

Generates Figures 3-9 (manuscript numbering), saved as both PNG (300 dpi) and PDF.
Figures 1-2 (world maps and graphical abstract) are generated by separate scripts.
"""

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
from scipy import stats

warnings.filterwarnings("ignore")

# ======================================================================
# PATHS
# ======================================================================
BASE = "/Users/mehranmamandipoor/Desktop/thesis/results"
QCI_PATH = os.path.join(BASE, "shared/qci.csv")
QCI_COMPLETE_PATH = os.path.join(BASE, "shared/qci_complete_data.csv")
AAPC_PATH = os.path.join(BASE, "shared/aapc_results.csv")
UNCERT_PATH = os.path.join(BASE, "shared/qci_uncertainty.csv")
OUT_DIR = os.path.join(BASE, "paper1/figures")
os.makedirs(OUT_DIR, exist_ok=True)

# ======================================================================
# GLOBAL STYLE - Lancet Global Health aesthetic
# ======================================================================
plt.rcParams.update({
    "font.family": "sans-serif",
    "font.sans-serif": ["Helvetica", "Arial", "DejaVu Sans"],
    "font.size": 10,
    "axes.titlesize": 12,
    "axes.labelsize": 11,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.linewidth": 0.8,
    "xtick.major.width": 0.6,
    "ytick.major.width": 0.6,
    "lines.linewidth": 1.8,
    "lines.markersize": 4,
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
})

# ======================================================================
# COLOUR PALETTES
# ======================================================================
REGION_COLORS = {
    "Global": "#000000",
    "Europe & Central Asia - WB": "#4C72B0",
    "North America": "#55A868",
    "East Asia & Pacific - WB": "#C44E52",
    "Latin America & Caribbean - WB": "#8172B2",
    "Middle East & North Africa - WB": "#CCB974",
    "South Asia - WB": "#64B5CD",
    "Sub-Saharan Africa - WB": "#DD8452",
}

REGION_LABELS = {
    "Global": "Global",
    "Europe & Central Asia - WB": "Europe & Central Asia",
    "North America": "North America",
    "East Asia & Pacific - WB": "East Asia & Pacific",
    "Latin America & Caribbean - WB": "Latin America & Caribbean",
    "Middle East & North Africa - WB": "Middle East & North Africa",
    "South Asia - WB": "South Asia",
    "Sub-Saharan Africa - WB": "Sub-Saharan Africa",
}

SDI_ORDER = ["High SDI", "High-middle SDI", "Middle SDI", "Low-middle SDI", "Low SDI"]
SDI_COLORS = {
    "High SDI": "#1a9850",
    "High-middle SDI": "#91cf60",
    "Middle SDI": "#fee08b",
    "Low-middle SDI": "#fc8d59",
    "Low SDI": "#d73027",
}

SDI_GROUP_ORDER = ["High", "High-middle", "Middle", "Low-middle", "Low"]
SDI_GROUP_COLORS = {
    "High": "#1a9850",
    "High-middle": "#91cf60",
    "Middle": "#fee08b",
    "Low-middle": "#fc8d59",
    "Low": "#d73027",
}

# ======================================================================
# LOAD DATA
# ======================================================================
print("Loading data...")
qci = pd.read_csv(QCI_PATH)
qci_full = pd.read_csv(QCI_COMPLETE_PATH)
aapc_df = pd.read_csv(AAPC_PATH)
uncert = pd.read_csv(UNCERT_PATH)
print("  qci.csv: " + str(qci.shape))
print("  qci_complete_data.csv: " + str(qci_full.shape))
print("  aapc_results.csv: " + str(aapc_df.shape))
print("  qci_uncertainty.csv: " + str(uncert.shape))


def savefig(fig, name):
    """Save figure as both PNG and PDF."""
    for ext in ("png", "pdf"):
        path = os.path.join(OUT_DIR, name + "." + ext)
        fig.savefig(path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print("  Saved: " + name + ".png / .pdf")


# ======================================================================
# FIGURE 3 (manuscript): Regional QCI Time Series (1990-2021)
# ======================================================================
def figure3():
    print("\nFigure 3: Regional QCI Time Series...")
    regions = list(REGION_COLORS.keys())
    mask = (
        (qci["location_name"].isin(regions))
        & (qci["age_name"] == "Age-standardized")
        & (qci["sex_name"] == "Both")
    )
    df = qci.loc[mask].copy()

    fig, ax = plt.subplots(figsize=(8, 5))

    for region in regions:
        sub = df[df["location_name"] == region].sort_values("year")
        lw = 2.5 if region == "Global" else 1.6
        zorder = 10 if region == "Global" else 5
        ax.plot(
            sub["year"], sub["pca_score"],
            color=REGION_COLORS[region],
            linewidth=lw,
            label=REGION_LABELS[region],
            zorder=zorder,
        )

    ax.set_xlabel("Year")
    ax.set_ylabel("Quality of Care Index (QCI)")
    ax.set_title("DS-TB Quality of Care Index by World Bank Region, 1990\u20132021")
    ax.set_xlim(1990, 2021)
    ax.set_ylim(88, 100)
    ax.yaxis.set_major_locator(ticker.MultipleLocator(2))
    ax.yaxis.set_minor_locator(ticker.MultipleLocator(1))
    ax.xaxis.set_major_locator(ticker.MultipleLocator(5))
    ax.grid(axis="y", alpha=0.3, linewidth=0.5)

    ax.legend(
        loc="upper center", bbox_to_anchor=(0.5, -0.14),
        ncol=4, frameon=False, fontsize=8.5,
    )
    fig.tight_layout()
    savefig(fig, "figure3_regional_qci_timeseries")


# ======================================================================
# FIGURE 4 (manuscript): SDI Gradient Plot - QCI vs SDI scatter (2021)
# ======================================================================
def figure4():
    print("\nFigure 4: SDI Gradient Scatter Plot...")
    mask = (
        (qci_full["year"] == 2021)
        & (qci_full["age_name"] == "Age-standardized")
        & (qci_full["sex_name"] == "Both")
        & (qci_full["sdi_group"].notna())
        & (qci_full["sdi_value_2021"].notna())
    )
    df = qci_full.loc[mask].copy()

    fig, ax = plt.subplots(figsize=(7, 5.5))

    for grp in SDI_GROUP_ORDER:
        sub = df[df["sdi_group"] == grp]
        ax.scatter(
            sub["sdi_value_2021"], sub["pca_score"],
            c=SDI_GROUP_COLORS[grp],
            edgecolors="white", linewidths=0.3,
            s=40, alpha=0.8, label=grp, zorder=5,
        )

    # Polynomial (degree 3) trend line
    x = df["sdi_value_2021"].values
    y = df["pca_score"].values
    valid = np.isfinite(x) & np.isfinite(y)
    x, y = x[valid], y[valid]
    z = np.polyfit(x, y, 3)
    p = np.poly1d(z)
    xfit = np.linspace(x.min(), x.max(), 200)
    ax.plot(xfit, p(xfit), color="#333333", linewidth=2,
            linestyle="--", zorder=10, label="Polynomial fit")

    # Spearman rho
    rho, pval = stats.spearmanr(x, y)
    pval_str = "P < 0.001" if pval < 0.001 else "P = " + str(round(pval, 3))
    annot_text = "Spearman \u03C1 = " + str(round(rho, 3)) + "\n" + pval_str
    ax.annotate(
        annot_text,
        xy=(0.03, 0.03), xycoords="axes fraction",
        fontsize=10, fontweight="bold",
        bbox=dict(boxstyle="round,pad=0.4", facecolor="white",
                  edgecolor="gray", alpha=0.9),
    )

    ax.set_xlabel("Socio-demographic Index (SDI), 2021")
    ax.set_ylabel("Quality of Care Index (QCI), 2021")
    ax.set_title("Association Between SDI and DS-TB Quality of Care Index, 2021")
    ax.grid(alpha=0.2, linewidth=0.4)
    ax.legend(
        loc="upper center", bbox_to_anchor=(0.5, -0.12),
        ncol=3, frameon=False, fontsize=9, markerscale=1.3,
    )
    fig.tight_layout()
    savefig(fig, "figure4_sdi_gradient_scatter")


# ======================================================================
# FIGURE 5 (manuscript): QCI by SDI Quintile Time Series (1990-2021)
# ======================================================================
def figure5():
    print("\nFigure 5: QCI by SDI Quintile Time Series...")
    mask = (
        (qci["location_name"].isin(SDI_ORDER))
        & (qci["age_name"] == "Age-standardized")
        & (qci["sex_name"] == "Both")
    )
    df = qci.loc[mask].copy()

    fig, ax = plt.subplots(figsize=(8, 5))

    for sdi in SDI_ORDER:
        sub = df[df["location_name"] == sdi].sort_values("year")
        ax.plot(
            sub["year"], sub["pca_score"],
            color=SDI_COLORS[sdi], linewidth=2.0,
            label=sdi, marker="o", markevery=5, markersize=4,
        )

    ax.set_xlabel("Year")
    ax.set_ylabel("Quality of Care Index (QCI)")
    ax.set_title("DS-TB Quality of Care Index by SDI Quintile, 1990\u20132021")
    ax.set_xlim(1990, 2021)
    ax.set_ylim(88, 100)
    ax.yaxis.set_major_locator(ticker.MultipleLocator(2))
    ax.yaxis.set_minor_locator(ticker.MultipleLocator(1))
    ax.xaxis.set_major_locator(ticker.MultipleLocator(5))
    ax.grid(axis="y", alpha=0.3, linewidth=0.5)

    for sdi in ["High SDI", "Low SDI"]:
        sub = df[df["location_name"] == sdi].sort_values("year")
        y2021 = sub[sub["year"] == 2021]["pca_score"].values[0]
        ax.annotate(
            str(round(y2021, 1)),
            xy=(2021, y2021), xytext=(2021.5, y2021),
            fontsize=8, color=SDI_COLORS[sdi],
            fontweight="bold", va="center",
        )

    ax.legend(
        loc="upper center", bbox_to_anchor=(0.5, -0.14),
        ncol=5, frameon=False, fontsize=8.5,
    )
    fig.tight_layout()
    savefig(fig, "figure5_sdi_quintile_timeseries")


# ======================================================================
# FIGURE 6 (manuscript): Component Ratios by Region - Heatmap (2021)
# ======================================================================
def figure6():
    print("\nFigure 6: Component Ratios by Region Heatmap...")
    regions = [
        "Europe & Central Asia - WB",
        "North America",
        "East Asia & Pacific - WB",
        "Latin America & Caribbean - WB",
        "Middle East & North Africa - WB",
        "South Asia - WB",
        "Sub-Saharan Africa - WB",
    ]
    mask = (
        (qci_full["location_name"].isin(regions))
        & (qci_full["year"] == 2021)
        & (qci_full["age_name"] == "Age-standardized")
        & (qci_full["sex_name"] == "Both")
    )
    df = qci_full.loc[mask, ["location_name", "MIR", "YLLtoYLD", "DALtoPER", "PERtoINC"]].copy()

    label_map = {
        "Europe & Central Asia - WB": "Europe & Central Asia",
        "North America": "North America",
        "East Asia & Pacific - WB": "East Asia & Pacific",
        "Latin America & Caribbean - WB": "Latin Am. & Caribbean",
        "Middle East & North Africa - WB": "Middle East & N. Africa",
        "South Asia - WB": "South Asia",
        "Sub-Saharan Africa - WB": "Sub-Saharan Africa",
    }
    df["region_label"] = df["location_name"].map(label_map)

    region_order = [
        "North America",
        "Europe & Central Asia",
        "East Asia & Pacific",
        "Latin Am. & Caribbean",
        "Middle East & N. Africa",
        "South Asia",
        "Sub-Saharan Africa",
    ]

    comp_cols = ["MIR", "YLLtoYLD", "DALtoPER", "PERtoINC"]
    component_labels = [
        "Mortality-to-\nIncidence Ratio",
        "YLL-to-YLD\nRatio",
        "DALY-to-\nPrevalence Ratio",
        "Prevalence-to-\nIncidence Ratio",
    ]

    df = df.set_index("region_label")
    df = df.loc[region_order, comp_cols]
    df_display = df.copy()

    # Normalise each column to 0-1 for colour mapping
    df_norm = df.copy()
    for col in df_norm.columns:
        cmin = df_norm[col].min()
        cmax = df_norm[col].max()
        if cmax > cmin:
            df_norm[col] = (df_norm[col] - cmin) / (cmax - cmin)
        else:
            df_norm[col] = 0.5

    fig, ax = plt.subplots(figsize=(7, 5.5))
    cmap = sns.color_palette("RdYlGn_r", as_cmap=True)

    sns.heatmap(
        df_norm, ax=ax, cmap=cmap,
        annot=df_display.round(3).values, fmt="",
        linewidths=1.5, linecolor="white",
        cbar_kws={"label": "Relative magnitude (normalised)", "shrink": 0.8},
        xticklabels=component_labels,
        yticklabels=region_order,
        annot_kws={"fontsize": 9, "fontweight": "bold"},
    )

    ax.set_title("DS-TB Component Ratios by World Bank Region, 2021", fontsize=12, pad=12)
    ax.set_ylabel("")  # Remove automatic "region_label" y-axis label
    ax.tick_params(axis="x", rotation=0, labelsize=9)
    ax.tick_params(axis="y", rotation=0, labelsize=9)
    fig.tight_layout()
    savefig(fig, "figure6_component_heatmap")


# ======================================================================
# FIGURE 7 (manuscript): Age-Sex QCI Heatmap - Global, 2021
# ======================================================================
def figure7():
    print("\nFigure 7: Age-Sex QCI Heatmap...")
    age_order = [
        "<5 years", "5-14 years", "15-49 years",
        "50-69 years", "70+ years", "Age-standardized",
    ]
    sex_order = ["Male", "Female", "Both"]

    mask = (
        (qci["location_name"] == "Global")
        & (qci["year"] == 2021)
        & (qci["age_name"].isin(age_order))
        & (qci["sex_name"].isin(sex_order))
    )
    df = qci.loc[mask, ["age_name", "sex_name", "pca_score"]].copy()

    pivot = df.pivot_table(index="age_name", columns="sex_name", values="pca_score")
    pivot = pivot.reindex(index=age_order, columns=sex_order)

    fig, ax = plt.subplots(figsize=(5.5, 5))
    sns.heatmap(
        pivot, ax=ax, annot=True, fmt=".2f", cmap="YlGnBu",
        linewidths=1.5, linecolor="white",
        cbar_kws={"label": "QCI", "shrink": 0.8},
        vmin=pivot.min().min() - 1,
        vmax=pivot.max().max() + 0.5,
        annot_kws={"fontsize": 11, "fontweight": "bold"},
    )
    ax.set_title("Global DS-TB QCI by Age Group and Sex, 2021", fontsize=12, pad=12)
    ax.set_xlabel("Sex", fontsize=11)
    ax.set_ylabel("Age Group", fontsize=11)
    ax.tick_params(axis="x", rotation=0, labelsize=10)
    ax.tick_params(axis="y", rotation=0, labelsize=10)
    fig.tight_layout()
    savefig(fig, "figure7_age_sex_heatmap")


# ======================================================================
# FIGURE 8 (manuscript): Country AAPC Forest Plot (Top 15 + Bottom 15)
# ======================================================================
def figure8():
    print("\nFigure 8: Country AAPC Forest Plot...")
    countries = aapc_df[aapc_df["category"] == "COUNTRY"].copy()
    countries = countries.sort_values("aapc_full", ascending=False)

    top15 = countries.head(15).copy()
    bot15 = countries.tail(15).copy()
    bot15 = bot15.sort_values("aapc_full", ascending=True)

    fig, (ax1, ax2) = plt.subplots(
        1, 2, figsize=(11, 7), sharey=False,
        gridspec_kw={"wspace": 0.45},
    )

    def _forest(ax, data, title, color):
        y_pos = np.arange(len(data))
        xerr_lo = data["aapc_full"].values - data["ci_lo_full"].values
        xerr_hi = data["ci_hi_full"].values - data["aapc_full"].values

        ax.errorbar(
            data["aapc_full"].values, y_pos,
            xerr=[xerr_lo, xerr_hi],
            fmt="o", color=color, ecolor=color,
            elinewidth=1.2, capsize=3, capthick=1,
            markersize=5, markeredgecolor="white",
            markeredgewidth=0.5, zorder=5,
        )
        ax.axvline(0, color="gray", linewidth=0.8, linestyle="--", alpha=0.6)
        ax.set_yticks(y_pos)
        ax.set_yticklabels(data["location"].values, fontsize=9)
        ax.set_xlabel("AAPC (% per year)", fontsize=10)
        ax.set_title(title, fontsize=11, fontweight="bold")
        ax.grid(axis="x", alpha=0.2, linewidth=0.4)

        for i, row in enumerate(data.itertuples()):
            val = row.aapc_full
            ci_lo = row.ci_lo_full
            ci_hi = row.ci_hi_full
            txt = "{:.3f} ({:.3f}, {:.3f})".format(val, ci_lo, ci_hi)
            x_offset = ci_hi + 0.015
            ax.text(x_offset, i, txt, fontsize=8, va="center", color="#444444")

    _forest(ax1, top15, "Top 15 Countries\n(Largest QCI Improvement)", "#1a9850")
    _forest(ax2, bot15, "Bottom 15 Countries\n(Smallest / Negative QCI Change)", "#d73027")

    for ax in (ax1, ax2):
        xmin, xmax = ax.get_xlim()
        ax.set_xlim(xmin - 0.05, xmax + 0.25)

    fig.suptitle(
        "Average Annual Percentage Change (AAPC) in DS-TB QCI, 1990\u20132021",
        fontsize=12, fontweight="bold", y=0.98,
    )
    fig.tight_layout(rect=[0, 0, 1, 0.95])
    savefig(fig, "figure8_aapc_forest_plot")


# ======================================================================
# FIGURE 9 (manuscript): QCI Uncertainty Plot (selected locations, 1990 vs 2021)
# ======================================================================
def figure9():
    print("\nFigure 9: QCI Uncertainty Plot...")
    df = uncert.copy()

    df90 = df[df["year"] == 1990].sort_values("sort_key").reset_index(drop=True)
    df21 = df[df["year"] == 2021].sort_values("sort_key").reset_index(drop=True)

    locations = df90["display_name"].values
    n = len(locations)
    y_pos = np.arange(n)

    fig, ax = plt.subplots(figsize=(9, 8))
    bar_offset = 0.18

    # 1990
    ax.errorbar(
        df90["qci_point"].values, y_pos + bar_offset,
        xerr=[
            df90["qci_point"].values - df90["qci_lower"].values,
            df90["qci_upper"].values - df90["qci_point"].values,
        ],
        fmt="s", color="#4C72B0", ecolor="#4C72B0",
        elinewidth=1.3, capsize=3, capthick=1,
        markersize=5, markeredgecolor="white",
        markeredgewidth=0.5, label="1990", zorder=5,
    )

    # 2021
    ax.errorbar(
        df21["qci_point"].values, y_pos - bar_offset,
        xerr=[
            df21["qci_point"].values - df21["qci_lower"].values,
            df21["qci_upper"].values - df21["qci_point"].values,
        ],
        fmt="o", color="#C44E52", ecolor="#C44E52",
        elinewidth=1.3, capsize=3, capthick=1,
        markersize=5, markeredgecolor="white",
        markeredgewidth=0.5, label="2021", zorder=5,
    )

    ax.set_yticks(y_pos)
    ax.set_yticklabels(locations, fontsize=9)
    ax.set_xlabel("Quality of Care Index (QCI)", fontsize=11)
    ax.set_title(
        "DS-TB Quality of Care Index with 95% Uncertainty Intervals\n"
        "Selected Locations, 1990 vs 2021",
        fontsize=12, fontweight="bold",
    )
    ax.invert_yaxis()
    ax.grid(axis="x", alpha=0.2, linewidth=0.4)
    ax.legend(loc="lower right", frameon=True, fontsize=10, framealpha=0.9)

    # Separator lines between groups
    for sep_y in [0.5, 5.5, 12.5]:
        if sep_y < n:
            ax.axhline(sep_y, color="gray", linewidth=0.5, linestyle=":", alpha=0.5)

    # Category labels
    category_labels = {0: "Global", 1: "SDI Quintiles", 6: "WB Regions", 13: "Countries"}
    for idx, label in category_labels.items():
        if idx < n:
            ax.annotate(
                label,
                xy=(1.01, y_pos[idx]),
                xycoords=("axes fraction", "data"),
                fontsize=8, fontweight="bold",
                color="#666666", va="center",
            )

    fig.tight_layout()
    savefig(fig, "figure9_qci_uncertainty")


# ======================================================================
# RUN ALL FIGURES
# ======================================================================
if __name__ == "__main__":
    print("=" * 60)
    print("Paper 1 Figure Generation")
    print("=" * 60)

    figure3()
    figure4()
    figure5()
    figure6()
    figure7()
    figure8()
    figure9()

    print()
    print("=" * 60)
    print("All figures generated successfully.")
    print("Output directory: " + OUT_DIR)
    print("=" * 60)
